### ISSUE TITLE
ingress_grpc.enabled=true helm install error

### ISSUE THREAD

**Issue by cyxinda** [dgraph-io/charts#107]
If ingress_grpc.enabled=true,some error would happend,like this:
```yaml
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: "dgraph.knowdee.com"
    # annotations: {}
    tls: 
    - hosts: 
      - dgraph.knowdee.com
      secretName: dgraph-dgraph-alpha-tls-secret

  ## alpha GRPC ingress resource configuration
  ## This requires an ingress controller to be installed into your k8s cluster
  ingress_grpc:
    enabled: true
    ingressClassName: nginx
    hostname: "grpc-dgraph.knowdee.com"
    annotations: 
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls: 
    - hosts: 
      - grpc-dgraph.knowdee.com
      secretName: dgraph-dgraph-alpha-tls-secret
```
```bash
        Helm install failed: error while running post render on files:
        map[string]interface {}(nil): yaml: unmarshal errors:
          line 31: mapping key "apiVersion" already defined at line 2
          line 32: mapping key "kind" already defined at line 3
          line 33: mapping key "metadata" already defined at line 4
          line 41: mapping key "spec" already defined at line 14
```
it is because there are the extra "-" in the file of dgraph/templates/alpha/ingress.yaml at the line 64.
![截图 2023-09-26 15-05-00](https://github.com/dgraph-io/charts/assets/7237898/99bd7faa-2e63-40cb-8061-b31322261a07)
it should remove the symbol "-".

the helm chart version is dgraph/dgraph:0.2.2  .
```bash
root@oldsix:/data2/tmp/dgraph/package# helm search repo dgraph
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
dgraph/dgraph           0.2.2           v23.0.1         Dgraph is a horizontally scalable and distribut...
dgraph/dgraph-lambda    0.0.2           v1.2.4          Serverless platform for running JavaScript on S...
dgraph/ratel            0.1.1           v21.12.0        A Helm chart for Kubernetes 
```

that all.
