### ISSUE TITLE
global grpc ingress yields two host key entries

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/charts#96]
### STEPS TO REPRODUCE

```bash
helm template ./charts/dgraph --values -  <<EOF
fullNameOverride: jmdg
global:
  ingress:
    enabled: true
    alpha_hostname: alpha.example.com
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
  ingress_grpc:
    enabled: true
    alpha_grpc_hostname: grpc.example.com
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
EOF
```

### ACTUAL RESULTS

```yaml
---
# Source: dgraph/templates/global-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-dgraph-ingress
  labels:
    app: dgraph
    chart: dgraph-0.1.0
    component: alpha
    release: release-name
    heritage: Helm
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - backend:
              service:
                name:  release-name-dgraph-alpha
                port:
                  number: 8080
            pathType: ImplementationSpecific
            path: /*
      host: alpha.example.com
---
# Source: dgraph/templates/global-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-dgraph-ingress-grpc
  labels:
    app: dgraph
    chart: dgraph-0.1.0
    component: alpha
    release: release-name
    heritage: Helm
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: grpc.example.com
      http:
        paths:
          - backend:
              service:
                name:  release-name-dgraph-alpha
                port:
                  number: 9080
            pathType: ImplementationSpecific
            path: /*
      host: grpc.example.com
```

### EXPTECTED RESULTS

The grpc should only have a single host key, e.g. 

```yaml
# Source: dgraph/templates/global-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-dgraph-ingress-grpc
  labels:
    app: dgraph
    chart: dgraph-0.1.0
    component: alpha
    release: release-name
    heritage: Helm
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - backend:
              service:
                name:  release-name-dgraph-alpha
                port:
                  number: 9080
            pathType: ImplementationSpecific
            path: /*
      host: grpc.example.com
```
