### ISSUE TITLE
Ratel chart does not support absent host in ingress

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/charts#98]
## OVERVIEW

Ratel requires a `host` key to be specified when creating an ingress.  In Kubernetes, if the key `host` is absent, then the `host: *` will be added as the key:value pair.  This is done should the operator want to deploy a single ALB as the load balancer, but choose to forego any HTTP based routing.

## STEPS TO REPRODUCE 

```bash
helm install ratel --namespace ratel --create-namespace ./charts/ratel/ --values - <<EOF
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - paths:
        - path: /*
          pathType: ImplementationSpecific
EOF
```

## EXPECTED RESULTS

If the `host` key is absent, then it should not be included rendered ingress output. 

## ACTUAL RESULTS

A `host` key without a value will be created, which will cause an error and prevent Ratel from being deployed.  

Specifically this is what is produced:

```yaml
# Source: ratel/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-ratel
  labels:
    helm.sh/chart: ratel-0.1.0
    app.kubernetes.io/name: ratel
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
# ERROR IS HERE
    - host:
# ABOVE CAUSES AN ERROR
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-ratel
                port:
                  number: 80
```

Notice the host key with no value.
